# specify which database and adapter to use for which environment

development:
  adapter: postgresql
  database: sinatra-app-development

test:
  adapter: postgresql
  database: sinatra-app-test

production:
  adapter: postgresql
  database: sinatra-app-production

